#!/bin/bash

echo "╔════════════════════════════════════════╗"
echo "║  Firebase Hosting Setup Helper        ║"
echo "╚════════════════════════════════════════╝"
echo

# Check if ngrok URL is provided
if [ -z "$1" ]; then
    echo "❌ Error: Ngrok URL required"
    echo
    echo "Usage: ./setup_firebase.sh YOUR_NGROK_URL"
    echo "Example: ./setup_firebase.sh https://abc123.ngrok.io"
    echo
    echo "Steps:"
    echo "1. Start your backend: cd backend && python3 main.py"
    echo "2. Start ngrok: ngrok http 8000"
    echo "3. Copy the ngrok URL from output"
    echo "4. Run this script: ./setup_firebase.sh https://your-url.ngrok.io"
    exit 1
fi

NGROK_URL=$1

# Remove trailing slash if present
NGROK_URL=${NGROK_URL%/}

echo "→ Updating config with ngrok URL: $NGROK_URL"

# Update config.js
cat > public/js/config.js << EOF
/**
 * API Configuration
 * Auto-generated by setup_firebase.sh
 */

// Firebase hosting with ngrok
const API_BASE_URL = '$NGROK_URL';

// WebSocket URL (same as API but ws:// or wss://)
const WS_BASE_URL = API_BASE_URL.replace('https://', 'wss://').replace('http://', 'ws://');
EOF

echo "✓ Config updated"
echo

# Test the API
echo "→ Testing API connection..."
if curl -s -f "$NGROK_URL/api/posts" > /dev/null; then
    echo "✓ API is accessible"
else
    echo "⚠ Warning: Could not reach API"
    echo "  Make sure backend is running and ngrok is active"
fi

echo
echo "╔════════════════════════════════════════╗"
echo "║  Ready to Deploy!                      ║"
echo "╚════════════════════════════════════════╝"
echo
echo "Next steps:"
echo "1. firebase deploy --only hosting"
echo "2. Visit your Firebase URL"
echo "3. Check forum for real-time updates!"
echo
echo "Configuration:"
echo "  API URL: $NGROK_URL"
echo "  WebSocket: ${NGROK_URL/https:\/\//wss://}/ws/forum"
echo
